### PR TITLE
Integrate RtD3s

### PR DESCRIPTION
**Pull request by hamishgibbs**
Integration of [RtD3js](https://github.com/hamishgibbs/RtD3js) React library with existing summaryWidget function. 

I have removed some of the data checks as they were quite complex and it may be easier to write up the desired data format in the docs, instead of testing for possible data faults when instantiating the widget. If input data is incorrect, the widget will not render correctly. I think the best way to troubleshoot this would be the docs, not custom error messages. 

Incorporates the new RtD3js library in the widget with new features (listed in the Readme). 

Items still needing attention:

- [x] Widget sizing. Should fit into a standard Rmd document (I think 900px width?) currently at an arbitrary 1000x1000 px. 

- [x] All tooltips have disappeared. This may be because they are absolutely positioned divs (which is a persistent problem for custom html widgets in Rmd documents). Resolving this may require a different approach, like an info panel - not a tooltip? We could drop tooltips temporarily to get up and running more quickly.

- [x] Hover line on the timeseries is not correctly aligned with pointer. This should be resolved after fixing item 1 or may need more attention.

- [x] issues with differences in `Region` `region` `country`, `Country` column names. This should be addressed in RtD3js by converting all possibilities to `region`. This is why the region selection dropdown is currently empty. @seabbs - does this seem like a safe approach? What if data is passed with both `Country` and `region` columns?

- [x] Some odd bootstrap spacing that should sort itself out (or will need sorting) when item 1 is handled. 

- [x] Add all default legend configurations to `default_map_legend_ref.R` (with actual colors for display).

**A potential issue:** I have used Bootstrap 4 in RtD3js to make spacing and styling everything easy. Hopefully this will not conflict with other templates that are rendered on the main site but I am not positive how all the different styles will play on a page with a different style if there are conflicting classnames and if the Bootstrap styles are not scoped to the widget. We will see.

### CODE REVIEW

**Review by seabbs — COMMENTED** [review]
Everything here so far looks very reasonable. 

Agree with all points. For the region and countries mixing I can see that maybe being an issue but I would go with getting a working solution (so only having one or other) for now. 

I have talked to Paul a bit about what they would want and they are interested in spatial hierarchies but I think that would be pretty non-trivial to get working. 

Agree on dropping tooltip for now in favour of transitioning to this implementation as its very nice.

**Comment by hamishgibbs** [comment]
Changes:

* remove tsWidget function.
* remove mapWidget function.
* remove check_input_data function - this will move to docs as described.
* adds data_ref prop which is passed to summaryWidget to define which columns hold the geometry that should be symbolised. This resolves the issues with `Region`, `Country`, `country`, `region` columns.
  * this comes with the `default_data_ref` function which returns defaults for data read with `readInEpiNow2`. 
* adds all default legends @seabbs please adjust these colors (and *probably* scales - untested) as you would like
* exposes activeArea prop to user.
* rounds sequential map legend labels to 2 decimals.
* resolves issues with default widget height and width.
* solved issues with map tooltip - now working fine.

To do:

- [x] Align pointer with ts hover line and tooltip. Still failing to align because of the spacing between left window and plot. Working on it.
- [x] Fix tests.
- [x] Update docs.

Should be working and ready to go soon.

**Comment by hamishgibbs** [comment]
Pointer now aligned. Pausing here - will be back to address tests and docs.

**Comment by hamishgibbs** [comment]
Fixed tests by eliminating most of the data structure checks. We can discuss what the best approach is but this makes the R code simpler and easier to maintain. Could lead to more uncaught JavaScript errors which are harder to debug in Rstudio (but you can checkout from a Rmd opened in Chrome). Hopefully the docs provide enough info on the anticipated data structure to troubleshoot odd widgets.

Updated docs. We still need some info on how to create custom map legends for different variables and add custom colors to the timeseries. This can be added in the future. 

Fixed various spelling errors and did a general review of docs.

**Review by seabbs — APPROVED** [review]
Looks good to me

**Pull request merged**
