### PR TITLE
Cran check

### PR DESCRIPTION
**Pull request by seabbs**
Updated to pass all CRAN checks.

### CODE REVIEW

**Comment by hamishgibbs** [comment]
I thought the URL issue was only affecting the `DESCRIPTION` file. This looks good - I will rerun checks locally and then resubmit. 

Thanks!

**Comment by seabbs** [comment]
I checked locally and looks like all good just checking I have the URL checks correctly in the local check. Its a bit confusing but the bit under the URL issue links to the README. I also added the spelling package here to clean up the spell check issues. It also adds a spell check when testing.

**Comment by seabbs** [comment]
Just corrected the install instructions for the dev package version and added drat install option.

**Comment by hamishgibbs** [comment]
All looks good - thanks!

**Pull request merged**
